name = "MakeshiftSMP"
author = "Thamatter"
version = "6.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71a3c9382108316efca9592c787af7f0836aefbf7d689401ac2b8a81309c6999"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
