name = "MakeshiftSMP"
author = "Thamatter"
version = "6.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e2be4c22409d1ff9591f258ef9de8d3d248b2a58a5233f5637b305653a412c8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
