name = "MakeshiftSMP"
author = "Thamatter"
version = "6.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c783e4dcbf76a4f2313057df5da63d45ff7d28e50b14d7d56dcba20be680f4fe"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
